apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: christel
  name: christel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
