apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: mysqlserver
  name: mysqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqlserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/petclinic-docker-chris: "true"
        io.kompose.service: mysqlserver
    spec:
      containers:
        - env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
            - name: MYSQL_DATABASE
              value: petclinic
            - name: MYSQL_PASSWORD
              value: petclinic
            - name: MYSQL_USER
              value: petclinic
          image: mysql:8
          name: mysqlserver
          volumeMounts:
            - mountPath: /etc/mysql/conf.d
              name: mysql-config
      restartPolicy: Always
      volumes:
        - name: mysql-config
          persistentVolumeClaim:
            claimName: mysql-config
