apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: sentinel-2
  name: sentinel-2
spec:
  ports:
    - name: "26380"
      port: 26380
      targetPort: 26379
  selector:
    io.kompose.service: sentinel-2
